spring:
  application:
    name: hr-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/summary_table
    username: root
    password: yyffyy200452
  # session 失效时间
  session:
    timeout: 86400
#    sql:
#      init:
#        schema-locations: jdbc:mysql://localhost:3306/summer_table
#        data-locations: jdbc:mysql://localhost:3306/summer_table
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
